version: '3.9'

services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: 'salama'
      MYSQL_DATABASE: 'test'
      MYSQL_USER: 'salama'
      MYSQL_PASSWORD: 'salama'
      MYSQL_ROOT_HOST: '%' # needs to be enclosed with quotes

    ports:
      - 3306:3306
    volumes:
      - ~/apps/mysql2:/var/lib/mysql
